### ISSUE TITLE
请问是否有视觉模型的参与呢

### ISSUE THREAD

**Issue by Just4Uzi** [NoneJou072/robochain#11]
请问下是不是有一些视觉模型的参与来判断摄像头内某个物体的位置呢？如果有的话是在代码哪里配置呢，我没找到视觉模型相关代码。如果没有使用视觉模型机械臂是如何判断小球、可乐罐等物体的具体位置呢

**Comment by NoneJou072** [comment]
这个项目没有使用到视觉模型，这些位置是从仿真中直接读取的
