### ISSUE TITLE
终端中启动 llm 服务端和 robot 客户端失败

### ISSUE THREAD

**Issue by zhuzj5** [NoneJou072/robochain#15]
我在安装依赖和编译时没有报错，但是在启动gpt_server和 gpt_client时显示Package 'gpt_server' not found

zj@zj-virtual-machine:~/Desktop/gpt_ws$ rosdep install --from-paths src --ignore-src -r -y
#All required rosdeps installed successfully
zj@zj-virtual-machine:~/Desktop/gpt_ws$ colcon build --symlink-install
Starting >>> gpt_interface
Finished <<< gpt_interface [0.61s]                     
Starting >>> gpt_client
Starting >>> gpt_server
Finished <<< gpt_server [1.76s]                                          
Finished <<< gpt_client [1.78s]

Summary: 3 packages finished [2.69s]
zj@zj-virtual-machine:~/Desktop/gpt_ws$ # Terminal 1
zj@zj-virtual-machine:~/Desktop/gpt_ws$ ros2 run gpt_server gpt_server
Package 'gpt_server' not found
zj@zj-virtual-machine:~/Desktop/gpt_ws$ # Terminal 2
zj@zj-virtual-machine:~/Desktop/gpt_ws$ ros2 run gpt_client gpt_client
Package 'gpt_client' not found

**Comment by DongRos** [comment]
你好 你解决了么 我也这样

**Comment by DongRos** [comment]
source ~/gpt_ws/install/setup.bash解决

**Comment by DongRos** [comment]
source ~/gpt_ws/install/setup.bash
