### ISSUE TITLE
关于所使用的大模型

### ISSUE THREAD

**Issue by LebinLiang** [NoneJou072/robochain#3]
因为没有获取到chatgpt的api，所以卡在了第一步。想问问是否可以使用其他大语言模型部署该仓库呢？

**Comment by NoneJou072** [comment]
抱歉现在才看到这个问题。langchain 提供了许多其它的大模型接口，可以去了解一下。或者可以去 tb 买个 chatgpt 的 api ，还挺便宜的。或者等我更 llama2 版本的这个仓库，最近几天就会更新。

**Comment by NoneJou072** [comment]
使用本地部署 codellama 模型的示例已推送到 v-llama2 分支
