### ISSUE TITLE
ROS2报错colcon build --symlink-install   ModuleNotFoundError: No module named 'em'

### ISSUE THREAD

**Issue by joker1499** [NoneJou072/robochain#7]
(ROBOPAL) linux@linux-Lenovo-Legion-R7000P2021H:~/ros_demo/gpt_ws$ colcon build --symlink-install
Starting >>> gpt_interface
--- stderr: gpt_interface                         
CMake Warning (dev) at /opt/ros/foxy/share/ament_cmake_core/cmake/core/python.cmake:22 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /opt/ros/foxy/share/ament_cmake_core/cmake/core/all.cmake:53 (include)
  /opt/ros/foxy/share/ament_cmake_core/cmake/ament_cmake_core-extras.cmake:17 (include)
  /opt/ros/foxy/share/ament_cmake_core/cmake/ament_cmake_coreConfig.cmake:41 (include)
  /opt/ros/foxy/share/ament_cmake/cmake/ament_cmake_export_dependencies-extras.cmake:15 (find_package)
  /opt/ros/foxy/share/ament_cmake/cmake/ament_cmakeConfig.cmake:41 (include)
  CMakeLists.txt:19 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /opt/ros/foxy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:40 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:25 (rosidl_generate_interfaces)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /opt/ros/foxy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
  execute_process(/home/linux/anaconda3/envs/ROBOPAL/bin/python3 -m
  rosidl_adapter --package-name gpt_interface --arguments-file
  /home/linux/ros_demo/gpt_ws/build/gpt_interface/rosidl_adapter__arguments__gpt_interface.json
  --output-dir
  /home/linux/ros_demo/gpt_ws/build/gpt_interface/rosidl_adapter/gpt_interface
  --output-file
  /home/linux/ros_demo/gpt_ws/build/gpt_interface/rosidl_adapter/gpt_interface.idls)
  returned error code 1:

  Traceback (most recent call last):

    File "/home/linux/anaconda3/envs/ROBOPAL/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/home/linux/anaconda3/envs/ROBOPAL/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
      sys.exit(main())
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
      abs_idl_file = convert_to_idl(
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 23, in convert_to_idl
      from rosidl_adapter.srv import convert_srv_to_idl
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/srv/__init__.py", line 16, in <module>
      from rosidl_adapter.resource import expand_template
    File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/resource/__init__.py", line 19, in <module>
      import em

  ModuleNotFoundError: No module named 'em'

Call Stack (most recent call first):
  /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
  CMakeLists.txt:25 (rosidl_generate_interfaces)

---
Failed   <<< gpt_interface [0.47s, exited with code 1]

Summary: 0 packages finished [2.38s]
  1 package failed: gpt_interface
  1 package had stderr output: gpt_interface
  2 packages not processed

**Comment by joker1499** [comment]
这个em包是什么

**Comment by joker1499** [comment]
已解决

**Comment by huangjie84** [comment]
怎么解决的。老兄
