### ISSUE TITLE
i find that i cannot solve that the lack of robopal and mujoco

### ISSUE THREAD

**Issue by xyys2003** [NoneJou072/robochain#8]
when i use 'ros2 run gpt_server gpt_server', it calls back that ModuleNotFoundError: No module named 'robopal' . 

I used pip list and conda list, but it showed that the robopal had existed. I tried to install it in the base instead of other Virtual Environments. But it did not work out. Could you tell me why? And to solve it, where should I install the robopal?

**Comment by NoneJou072** [comment]
robopal is one of my projects, now you can only download it from my [repo](https://github.com/NoneJou072/robopal.git). 
I have indicated the link to this library in the readme, but it may not be very clear, sorry
